package controller

import (
	"encoding/binary"
	"sync"
	"time"

	"github.com/pkg/errors"

	"project/internal/convert"
	"project/internal/guid"
	"project/internal/logger"
	"project/internal/xpanic"
)

// syncer is used to make sure every one message will
// be handle once, and start a cleaner to release memory.
type syncer struct {
	ctx *Ctrl

	expireTime int64

	// value = timestamp
	nodeSendGUID      map[guid.GUID]int64
	nodeSendGUIDRWM   sync.RWMutex
	nodeAckGUID       map[guid.GUID]int64
	nodeAckGUIDRWM    sync.RWMutex
	beaconSendGUID    map[guid.GUID]int64
	beaconSendGUIDRWM sync.RWMutex
	beaconAckGUID     map[guid.GUID]int64
	beaconAckGUIDRWM  sync.RWMutex
	queryGUID         map[guid.GUID]int64
	queryGUIDRWM      sync.RWMutex

	// convert guid []byte to *guid.GUID
	mapKeyPool sync.Pool

	stopSignal chan struct{}
	wg         sync.WaitGroup
}

func newSyncer(ctx *Ctrl, config *Config) (*syncer, error) {
	cfg := config.Syncer

	if cfg.ExpireTime < 3*time.Second || cfg.ExpireTime > 30*time.Second {
		return nil, errors.New("expire time < 3 seconds or > 30 seconds")
	}

	syncer := syncer{
		ctx:            ctx,
		expireTime:     int64(cfg.ExpireTime.Seconds()),
		nodeSendGUID:   make(map[guid.GUID]int64),
		nodeAckGUID:    make(map[guid.GUID]int64),
		beaconSendGUID: make(map[guid.GUID]int64),
		beaconAckGUID:  make(map[guid.GUID]int64),
		queryGUID:      make(map[guid.GUID]int64),
		stopSignal:     make(chan struct{}),
	}
	syncer.mapKeyPool.New = func() interface{} {
		return new(guid.GUID)
	}
	syncer.wg.Add(1)
	go syncer.guidCleaner()
	return &syncer, nil
}

// CheckGUIDSliceTimestamp is used to check GUID is expire, parameter is []byte
func (syncer *syncer) CheckGUIDSliceTimestamp(guid []byte) bool {
	// look internal/guid/guid.go to understand guid[20:28]
	timestamp := int64(binary.BigEndian.Uint64(guid[20:28]))
	now := syncer.ctx.global.Now().Unix()
	return convert.AbsInt64(now-timestamp) > syncer.expireTime
}

// CheckGUIDTimestamp is used to check GUID is expire
func (syncer *syncer) CheckGUIDTimestamp(guid *guid.GUID) (bool, int64) {
	now := syncer.ctx.global.Now().Unix()
	timestamp := guid.Timestamp()
	return convert.AbsInt64(now-timestamp) > syncer.expireTime, timestamp
}

// --------------------------code generated by resource/code/syncer.go-----------------------------

func (syncer *syncer) CheckNodeSendGUIDSlice(slice []byte) bool {
	key := syncer.mapKeyPool.Get().(*guid.GUID)
	defer syncer.mapKeyPool.Put(key)
	copy(key[:], slice)
	syncer.nodeSendGUIDRWM.RLock()
	defer syncer.nodeSendGUIDRWM.RUnlock()
	_, ok := syncer.nodeSendGUID[*key]
	return !ok
}

func (syncer *syncer) CheckNodeAckGUIDSlice(slice []byte) bool {
	key := syncer.mapKeyPool.Get().(*guid.GUID)
	defer syncer.mapKeyPool.Put(key)
	copy(key[:], slice)
	syncer.nodeAckGUIDRWM.RLock()
	defer syncer.nodeAckGUIDRWM.RUnlock()
	_, ok := syncer.nodeAckGUID[*key]
	return !ok
}

func (syncer *syncer) CheckBeaconSendGUIDSlice(slice []byte) bool {
	key := syncer.mapKeyPool.Get().(*guid.GUID)
	defer syncer.mapKeyPool.Put(key)
	copy(key[:], slice)
	syncer.beaconSendGUIDRWM.RLock()
	defer syncer.beaconSendGUIDRWM.RUnlock()
	_, ok := syncer.beaconSendGUID[*key]
	return !ok
}

func (syncer *syncer) CheckBeaconAckGUIDSlice(slice []byte) bool {
	key := syncer.mapKeyPool.Get().(*guid.GUID)
	defer syncer.mapKeyPool.Put(key)
	copy(key[:], slice)
	syncer.beaconAckGUIDRWM.RLock()
	defer syncer.beaconAckGUIDRWM.RUnlock()
	_, ok := syncer.beaconAckGUID[*key]
	return !ok
}

func (syncer *syncer) CheckQueryGUIDSlice(slice []byte) bool {
	key := syncer.mapKeyPool.Get().(*guid.GUID)
	defer syncer.mapKeyPool.Put(key)
	copy(key[:], slice)
	syncer.queryGUIDRWM.RLock()
	defer syncer.queryGUIDRWM.RUnlock()
	_, ok := syncer.queryGUID[*key]
	return !ok
}

func (syncer *syncer) CheckNodeSendGUID(guid *guid.GUID, timestamp int64) bool {
	syncer.nodeSendGUIDRWM.Lock()
	defer syncer.nodeSendGUIDRWM.Unlock()
	if _, ok := syncer.nodeSendGUID[*guid]; ok {
		return false
	}
	syncer.nodeSendGUID[*guid] = timestamp
	return true
}

func (syncer *syncer) CheckNodeAckGUID(guid *guid.GUID, timestamp int64) bool {
	syncer.nodeAckGUIDRWM.Lock()
	defer syncer.nodeAckGUIDRWM.Unlock()
	if _, ok := syncer.nodeAckGUID[*guid]; ok {
		return false
	}
	syncer.nodeAckGUID[*guid] = timestamp
	return true
}

func (syncer *syncer) CheckBeaconSendGUID(guid *guid.GUID, timestamp int64) bool {
	syncer.beaconSendGUIDRWM.Lock()
	defer syncer.beaconSendGUIDRWM.Unlock()
	if _, ok := syncer.beaconSendGUID[*guid]; ok {
		return false
	}
	syncer.beaconSendGUID[*guid] = timestamp
	return true
}

func (syncer *syncer) CheckBeaconAckGUID(guid *guid.GUID, timestamp int64) bool {
	syncer.beaconAckGUIDRWM.Lock()
	defer syncer.beaconAckGUIDRWM.Unlock()
	if _, ok := syncer.beaconAckGUID[*guid]; ok {
		return false
	}
	syncer.beaconAckGUID[*guid] = timestamp
	return true
}

func (syncer *syncer) CheckQueryGUID(guid *guid.GUID, timestamp int64) bool {
	syncer.queryGUIDRWM.Lock()
	defer syncer.queryGUIDRWM.Unlock()
	if _, ok := syncer.queryGUID[*guid]; ok {
		return false
	}
	syncer.queryGUID[*guid] = timestamp
	return true
}

func (syncer *syncer) Close() {
	close(syncer.stopSignal)
	syncer.wg.Wait()
	syncer.ctx = nil
}

// guidCleaner is use to clean expire guid
func (syncer *syncer) guidCleaner() {
	defer func() {
		if r := recover(); r != nil {
			b := xpanic.Print(r, "syncer.guidCleaner")
			syncer.ctx.logger.Print(logger.Fatal, "syncer", b)
			// restart GUID cleaner
			time.Sleep(time.Second)
			go syncer.guidCleaner()
		} else {
			syncer.wg.Done()
		}
	}()
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	count := 0
	max := int(syncer.expireTime)
	for {
		select {
		case <-ticker.C:
			syncer.cleanGUID()
			count++
			if count > max {
				syncer.cleanGUIDMap()
				count = 0
			}
		case <-syncer.stopSignal:
			return
		}
	}
}

func (syncer *syncer) cleanGUID() {
	now := syncer.ctx.global.Now().Unix()
	syncer.cleanNodeSendGUID(now)
	syncer.cleanNodeAckGUID(now)
	syncer.cleanBeaconSendGUID(now)
	syncer.cleanBeaconAckGUID(now)
	syncer.cleanQueryGUID(now)
}

func (syncer *syncer) cleanNodeSendGUID(now int64) {
	syncer.nodeSendGUIDRWM.Lock()
	defer syncer.nodeSendGUIDRWM.Unlock()
	for key, timestamp := range syncer.nodeSendGUID {
		if convert.AbsInt64(now-timestamp) > syncer.expireTime {
			delete(syncer.nodeSendGUID, key)
		}
	}
}

func (syncer *syncer) cleanNodeAckGUID(now int64) {
	syncer.nodeAckGUIDRWM.Lock()
	defer syncer.nodeAckGUIDRWM.Unlock()
	for key, timestamp := range syncer.nodeAckGUID {
		if convert.AbsInt64(now-timestamp) > syncer.expireTime {
			delete(syncer.nodeAckGUID, key)
		}
	}
}

func (syncer *syncer) cleanBeaconSendGUID(now int64) {
	syncer.beaconSendGUIDRWM.Lock()
	defer syncer.beaconSendGUIDRWM.Unlock()
	for key, timestamp := range syncer.beaconSendGUID {
		if convert.AbsInt64(now-timestamp) > syncer.expireTime {
			delete(syncer.beaconSendGUID, key)
		}
	}
}

func (syncer *syncer) cleanBeaconAckGUID(now int64) {
	syncer.beaconAckGUIDRWM.Lock()
	defer syncer.beaconAckGUIDRWM.Unlock()
	for key, timestamp := range syncer.beaconAckGUID {
		if convert.AbsInt64(now-timestamp) > syncer.expireTime {
			delete(syncer.beaconAckGUID, key)
		}
	}
}

func (syncer *syncer) cleanQueryGUID(now int64) {
	syncer.queryGUIDRWM.Lock()
	defer syncer.queryGUIDRWM.Unlock()
	for key, timestamp := range syncer.queryGUID {
		if convert.AbsInt64(now-timestamp) > syncer.expireTime {
			delete(syncer.queryGUID, key)
		}
	}
}

func (syncer *syncer) cleanGUIDMap() {
	syncer.cleanNodeSendGUIDMap()
	syncer.cleanNodeAckGUIDMap()
	syncer.cleanBeaconSendGUIDMap()
	syncer.cleanBeaconAckGUIDMap()
	syncer.cleanQueryGUIDMap()
}

func (syncer *syncer) cleanNodeSendGUIDMap() {
	syncer.nodeSendGUIDRWM.Lock()
	defer syncer.nodeSendGUIDRWM.Unlock()
	newMap := make(map[guid.GUID]int64, len(syncer.nodeSendGUID))
	for key, timestamp := range syncer.nodeSendGUID {
		newMap[key] = timestamp
	}
	syncer.nodeSendGUID = newMap
}

func (syncer *syncer) cleanNodeAckGUIDMap() {
	syncer.nodeAckGUIDRWM.Lock()
	defer syncer.nodeAckGUIDRWM.Unlock()
	newMap := make(map[guid.GUID]int64, len(syncer.nodeAckGUID))
	for key, timestamp := range syncer.nodeAckGUID {
		newMap[key] = timestamp
	}
	syncer.nodeAckGUID = newMap
}

func (syncer *syncer) cleanBeaconSendGUIDMap() {
	syncer.beaconSendGUIDRWM.Lock()
	defer syncer.beaconSendGUIDRWM.Unlock()
	newMap := make(map[guid.GUID]int64, len(syncer.beaconSendGUID))
	for key, timestamp := range syncer.beaconSendGUID {
		newMap[key] = timestamp
	}
	syncer.beaconSendGUID = newMap
}

func (syncer *syncer) cleanBeaconAckGUIDMap() {
	syncer.beaconAckGUIDRWM.Lock()
	defer syncer.beaconAckGUIDRWM.Unlock()
	newMap := make(map[guid.GUID]int64, len(syncer.beaconAckGUID))
	for key, timestamp := range syncer.beaconAckGUID {
		newMap[key] = timestamp
	}
	syncer.beaconAckGUID = newMap
}

func (syncer *syncer) cleanQueryGUIDMap() {
	syncer.queryGUIDRWM.Lock()
	defer syncer.queryGUIDRWM.Unlock()
	newMap := make(map[guid.GUID]int64, len(syncer.queryGUID))
	for key, timestamp := range syncer.queryGUID {
		newMap[key] = timestamp
	}
	syncer.queryGUID = newMap
}
